- name: play-01
  hosts: web
  tasks: 
   - name: PLAY-01 TASK-01
     ansible.builtin.debug:                          # ansible.builtin.debug is used to print a module in ansible just like echo in linux