- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"  #without the pipeline  and deafultof () it will through undefined variable error if you give just {{ course}}.
  
  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"
  
  - name: get the unique values
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "sivakumar reddy"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}" #dict2items is a filter in ansible to convert map into lists.

  - name: convert list to map
    vars:
      course:
      - { "key": "name","value": "DevOps with AWS" }
      - { "key": "duration","value": 120 }
      - { "key": "trainer","value": "sivakumar reddy" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"      #items2dict is a filter in ansible to convert lists into Map.

  - name: check ip address
    vars:
      myip: "172.31.39.17"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"    #ansible.utils.ipv4 is a filter to check your ip is crrect or wrong.