- name: command vs shell  #are two modules in ansible where command is used for simple commands, and shell is used for complex 
                            #commands(pipelines,shell, redirectors)
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute command inside
    # command module, just issues the command and it more secure than shell as shell go inside the server when we run shell command.

  - name: check the process
    ansible.builtin.command: ps -ef | grep ssh
    register: output

  # - name: check the process
  #   ansible.builtin.command: ps -ef | grep ssh
  #   register: output